version: "3.9"

services:
  postgres:
    image: postgres:16

    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - ".env"
    ports:
      - "5432:5432"
  backend:
    build:
      context: "."
      dockerfile: "Dockerfile"
    command: "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    restart: always
    env_file:
      - ".env"
    environment:
      - POSTGRES_HOST=postgres
    ports:
      - "8000:8000"
  minio:
    image: minio/minio
    ports:
      - "10000:9000"
      - "10001:9001"
    volumes:
      - minio_storage:/data
    env_file:
      - ".env"
    command: server --console-address ":9001" /data

volumes:
  postgres-data:
  minio_storage:
